name: Push to main

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: url-shortener
  IMAGE_GOOGLE_CLOUD_TAG: ${{ env.GOOGLE_CLOUD_REGISTRY_HOSTNAME }}/${{ env.GOOGLE_CLOUD_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

jobs:
  google-cloud-auth:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS_JSON }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Configure docker'
        run: gcloud auth configure-docker

      - name: 'Build docker image'
        run: docker build . -t ${{ env.IMAGE_GOOGLE_CLOUD_TAG }}

      - name: 'Push docker image'
        run: docker push ${{ env.IMAGE_GOOGLE_CLOUD_TAG }}